# Generated by Django 4.2.10 on 2024-02-21 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='camp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.camp'),
        ),
    ]
