# Generated by Django 4.2.10 on 2024-02-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_kid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kid',
            name='emergency_contact',
            field=models.CharField(max_length=25),
        ),
    ]
