# Generated by Django 4.2.10 on 2024-02-27 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_kid_emergency_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camp',
            name='user',
        ),
    ]
