# Generated by Django 4.2.10 on 2024-02-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_camp_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='kids',
            field=models.ManyToManyField(related_name='camps', to='main_app.kid'),
        ),
    ]
